# Generated by Django 6.0.5 on 2026-05-08 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Şablon Adı')),
                ('content', models.TextField(verbose_name='Mesaj İçeriği')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Mesaj Şablonu',
                'verbose_name_plural': 'Mesaj Şablonları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='Anahtar')),
                ('value', models.TextField(verbose_name='Değer')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ayar',
                'verbose_name_plural': 'Ayarlar',
            },
        ),
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Grup Adı')),
                ('chat_id', models.CharField(max_length=100, unique=True, verbose_name='Chat ID')),
                ('bot_token', models.CharField(max_length=150, verbose_name='Bot Token')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Grubu',
                'verbose_name_plural': 'Telegram Grupları',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField(verbose_name='Mesaj İçeriği')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('success', 'Başarılı'), ('failed', 'Başarısız')], default='pending', max_length=20, verbose_name='Durum')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Gönderilen Sayı')),
                ('failed_count', models.IntegerField(default=0, verbose_name='Başarısız Sayı')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Gönderim Zamanı')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.messagetemplate', verbose_name='Şablon')),
                ('groups', models.ManyToManyField(to='core.telegramgroup', verbose_name='Gruplar')),
            ],
            options={
                'verbose_name': 'Mesaj Logu',
                'verbose_name_plural': 'Mesaj Logları',
                'ordering': ['-created_at'],
            },
        ),
    ]
