# Generated by Django 6.0.5 on 2026-05-08 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramgroup',
            name='bot_token',
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Görev Adı')),
                ('interval_minutes', models.IntegerField(default=60, verbose_name='Aralık (dk)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='Son Çalışma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(to='core.telegramgroup', verbose_name='Gruplar')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.messagetemplate', verbose_name='Şablon')),
            ],
            options={
                'verbose_name': 'Planlanmış Görev',
                'verbose_name_plural': 'Planlanmış Görevler',
                'ordering': ['-created_at'],
            },
        ),
    ]
