from django.urls import path
from . import views
from webhook_bot import webhook, set_webhook, delete_webhook

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('webhook/', webhook, name='webhook'),
    path('webhook/set/', set_webhook, name='set_webhook'),
    path('webhook/delete/', delete_webhook, name='delete_webhook'),
    path('gruplar/', views.group_list, name='groups'),
    path('gruplar/ekle/', views.group_add, name='group_add'),
    path('gruplar/sil/<int:pk>/', views.group_delete, name='group_delete'),
    path('gruplar/durum/<int:pk>/', views.group_toggle, name='group_toggle'),
    path('gruplar/tx-takip/<int:pk>/', views.group_toggle_tracker, name='group_toggle_tracker'),
    path('ayarlar/', views.settings_view, name='settings'),
    path('sablonlar/', views.templates, name='templates'),
    path('sablonlar/ekle/', views.template_add, name='template_add'),
    path('sablonlar/duzenle/<int:pk>/', views.template_edit, name='template_edit'),
    path('sablonlar/sil/<int:pk>/', views.template_delete, name='template_delete'),
    path('gonder/', views.send_message_view, name='send_message'),
    path('gonder/gonder/', views.send_message, name='send'),
    path('planli/', views.scheduled_tasks, name='scheduled_tasks'),
    path('planli/ekle/', views.scheduled_task_add, name='scheduled_task_add'),
    path('planli/durum/<int:pk>/', views.scheduled_task_toggle, name='scheduled_task_toggle'),
    path('planli/sil/<int:pk>/', views.scheduled_task_delete, name='scheduled_task_delete'),
    path('planli/duzenle/<int:pk>/', views.scheduled_task_edit, name='scheduled_task_edit'),
    path('kripto/', views.tx_tracker_dashboard, name='tx_tracker'),
    path('kripto/ara/', views.tx_lookup, name='tx_lookup'),
    path('kripto/grup/aktif/<int:pk>/', views.tx_enable_group, name='tx_enable_group'),
    path('kripto/grup/pasif/<int:pk>/', views.tx_disable_group, name='tx_disable_group'),
    path('kripto/grup/test/<int:pk>/', views.tx_send_test, name='tx_send_test'),
    path('kripto/test-temizle/', views.tx_clear_test_result, name='tx_clear_test_result'),
    path('api/logs/', views.get_logs, name='get_logs'),
    path('api/template/<int:pk>/', views.get_template, name='get_template'),
    path('api/tx-rates/', views.tx_rates_api, name='tx_rates_api'),
]